services:

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: /bin/sh -c "ollama serve & sleep 3 && ollama pull ${LLM_MODEL} && wait"

  agent-weather:
    container_name: agent-weather
    image: tools-weather
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${LLM_MODEL}
      - OLLAMA_BASE_URL=http://ollama:11434/v1
    depends_on:
      - ollama
    restart: unless-stopped

  streamlit:
    container_name: streamlit
    image: streamlit-weather
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    environment:
      - AGENT_WEATHER_URL=http://agent-weather:8000/ask
    depends_on:
      - agent-weather
    restart: unless-stopped

volumes:
  ollama: