services:

  ollama:
    container_name: ollama
    image: ollama/ollama

    # runtime: nvidia
    environment:
    #  NVIDIA_VISIBLE_DEVICES: "all"
    #  OLLAMA_KV_CACHE_TYPE: "q8_0"
      OLLAMA_KV_CACHE_TYPE: "q4_0" # https://mitjamartini.com/blog/kv-cache-quantization-in-ollama/
      OLLAMA_KEEP_ALIVE: "24h"
      OLLAMA_MAX_LOADED_MODELS: "1"
      OLLAMA_FLASH_ATTENTION: "1"
    shm_size: 2g
    healthcheck:
      test: [ "CMD", "ollama", "list", "||", "exit", "1" ]
      interval: 60s
      timeout: 30s
      retries: 5

    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: /bin/sh -c "ollama serve & sleep 3 && ollama pull ${LLM_MODEL} && wait"

  agent-weather:
    container_name: agent-weather
    image: tools-weather
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${LLM_MODEL}
      - OLLAMA_BASE_URL=http://ollama:11434/v1
    depends_on:
      - ollama
    restart: unless-stopped

  streamlit:
    container_name: streamlit
    image: streamlit-weather
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    environment:
      - AGENT_WEATHER_URL=http://agent-weather:8000/ask
      - TIMEOUT_REQUEST_AGENT=600 # 10 minutes - côté nginx mettre proxy_read_timeout 600;

      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
#      - STREAMLIT_SERVER_BASE_URL_PATH=/weather/
    depends_on:
      - agent-weather
    restart: unless-stopped

volumes:
  ollama:
